import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    height: '100%',
  },

  container2: {
    backgroundColor: '#00008B',
    height: '100%',
  },

  p: {
    margin: 0,
  },

  background: {
    width: 375,
    height: 268,
    backgroundColor: 'black',
  },

  backButtonContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 1,
    paddingHorizontal: 10,
    paddingTop: 30,
  },

  title: {
    position: 'absolute',
    top: 0,
    left: 40,
    right: -80,
    zIndex: 1,
    paddingHorizontal: 10,
    paddingTop: 85,
    color: 'white',
    fontFamily: 'System',
    fontSize: 40,
  },

  History1: {
    position: 'relative',
    width: 350,
    height: 149,
    top: 20,
    marginBottom: 20,
    left: 20,
    borderRadius: 8,
    boxSizing: 'border-box',
    backgroundColor: 'rgba(255,255,255,1)',
  },
  Group6310: {
    position: 'absolute',
    top: 15.92,
    display: 'flex',
    flexDirection: 'column',
    // width: 197.48,
    // height: 67.08,
    boxSizing: 'border-box',
  },
  _7958SwiftVillage: {
    color: 'rgba(36,46,66,1)',
    fontSize: 17,
    left: 45,
    lineHeight: 17,
    fontFamily: 'System',
    fontWeight: 400,
  },
  _105WilliamStChic: {
    color: 'rgba(36,46,66,1)',
    top: 36,
    fontSize: 17,
    left: 45,
    lineHeight: 17,
    fontFamily: 'System',
    fontWeight: 400,
  },
  Line2: {
    position: 'absolute',
    top: '22.09%',
    bottom: '56.43%',
    left: '7.27%',
    right: '91.86%',
    width: 3,
    height: 32,
  },
  Oval: {
    position: 'absolute',
    top: '10.0%',
    bottom: '75.22%',
    left: '4.65%',
    right: '89.24%',
    width: 21,
    height: 21,
  },
  Oval1: {
    position: 'absolute',
    top: '14.0%',
    bottom: '78.91%',
    left: '6.1%',
    right: '90.84%',
    width: 10.5,
    height: 10.5,
  },
  Oval2: {
    position: 'absolute',
    top: 65,
    left: 17,
    width: 18.52,
    height: 24.08,
  },
  Group166: {
    // position: 'relative',
    top: 105,
    display: 'flex',
    // flexDirection: 'column',
    // alignItems: 'center',
    width: '100%',
    height: 38,
    // paddingHorizontal: 0,
    // boxSizing: 'border-box',
  },
  Line: {
    width: '100%',
    height: 3,
    marginBottom: 10,
  },
  Group263: {
    // display: 'flex',
    flexDirection: 'row',
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
    // width: '100%',
    // boxSizing: 'border-box',
  },
  IconsMoney1: {
    width: 30,
    height: '100%',
    left: 15,
  },
  _7500: {
    color: 'rgba(36,46,66,1)',
    fontSize: 17,
    // lineHeight: 17,
    left: 15,
    fontFamily: 'System',
    fontWeight: '600',
  },

  button: {
    width: 350,
    height: 55,
    backgroundColor: '#FFFF', // white button background color
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },

  Confirm: {
    // display: 'flex',
    // flexDirection: 'column',
    // justifyContent: 'flex-end',
    color: 'rgba(66,82,255,1)',
    fontSize: 15,
    lineHeight: 15,
    fontFamily: 'System',
    fontWeight: '600',
    paddingLeft: 200,
    // textAlign: 'right',
    // left: 150,
  },
  IconsArrowLeft: {
    width: 20,
    height: 20,
    // left: 150,
  },
});
